name: build-site
on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'preview/**'
      - 'subsite/**'
jobs:
  build-site:
    env:
      OUTPUT_SITE_FOLDER: 'site'
      REPO_FOLDER: 'my-repo'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: https://${{ github.actor }}:${{ secrets.PAT }}@github.com

    - name: Install deps
      run: ./scripts/install_requirements.sh

    - name: Setup git config
      run: ./scripts/setup_git_configuration.sh

    - name: Render site
      run: make build

    - name: Copy site
      run: |
        export ENV_REF=${{ github.ref }}
        ./scripts/move_site_to_branch.sh

    - name: Push to Github pages
      run: |
        export ENV_REF=${{ github.ref }}
        export ENV_COMMIT_MSG=${{ env.CI_COMMIT_MESSAGE }}
        ./scripts/push_to_github_pages.sh

