name: build-site
on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'preview/**'
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Install deps
      run: sudo apt install pandoc
    - name: Render site
      run: |
        exec ./build.sh
        ls



