name: build-site
on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'preview/**'
jobs:
  build-site:
    env:
      OUTPUT_SITE_FOLDER: 'site'
      REPO_FOLDER: 'my-repo'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: https://${{ github.actor }}:${{ secrets.PAT }}@github.com

    - name: Install deps
      run: sudo apt install pandoc=2.5-3build2

    - name: Setup git config
      run: |
        export email=$(git log -n 1 --pretty=format:%ae)
        export name=$(git log -n 1 --pretty=format:%an)
        rm -rf .git
        git clone https://github.com/MariposaGentil/MariposaGentil.github.io ${REPO_FOLDER}
        cd ${REPO_FOLDER}
        git config --local user.email "$email"
        git config --local user.name "$name"

    - name: Render site
      run: |
        export branch=${{ github.ref }}
        export branch=$(sed 's/refs-heads-/''/' <<< ${branch//'/'/-})
        if [ "${branch}" = 'master' ]; then export dst_folder=''; else export dst_folder="subsite/${branch}"; fi
        echo ${dst_folder}
        exec ./build.sh
        mkdir -p ${REPO_FOLDER}/${dst_folder}/
        cp -r -v ${OUTPUT_SITE_FOLDER}/* ${REPO_FOLDER}/${dst_folder}/
        echo $(ls ${REPO_FOLDER}/${dst_folder})

    - name: Push to Github pages
      run: |
        cd ${REPO_FOLDER}
        git add .
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}  Automated commit generated from Gihub acions in cocoon repo"
        git push

