name: remove-subsite
on:
  - workflow_dispatch
  - delete
jobs:
  remove-subsite:
    runs-on: ubuntu-latest
    env:
      REPO_FOLDER: 'cocoon'
    steps:
    - uses: actions/checkout@v3
    - uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: https://${{ github.actor }}:${{ secrets.PAT }}@github.com

    - name: Download cocoon-site
      run: |
        ./scripts/download_cocoon_site.sh

    - name: Remove subsite folder
      run: |
        export branch=${{ github.event.ref }}
        ./scripts/remove_subsite_folder.sh
    - name: Push to cocoon-site
      run: |
        export ENV_REF=${{ github.ref }}
        export ENV_COMMIT_MSG=${{ env.CI_COMMIT_MESSAGE }}
        ./scripts/push_to_github_pages.sh --remove

